"""initial migration

Revision ID: 83d303bf4df7
Revises: 83450a41ec3b
Create Date: 2025-02-04 03:15:57.976220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d303bf4df7'
down_revision = '83450a41ec3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('oi_id', sa.String(length=36), nullable=False),
    sa.Column('i_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('other_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['i_id'], ['product_items.i_id'], ),
    sa.PrimaryKeyConstraint('oi_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('o_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('i_', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'order_items', ['i_'], ['i_id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('i_')
        batch_op.drop_column('total_price')
        batch_op.drop_column('o_id')

    op.drop_table('order_items')
    # ### end Alembic commands ###
